#pragma once
#define GEOMETRIA_H
#include "../Graphics/Cores/MainAPI/Graphics.h"
#include "../Graphics/Cores/Renderer/RendererCore.h"
#include "../Graphics/Externals/SceneAndDrawCall.h"
#include "../Input/Input.h"
#include "../Files/Files.h"
#include "../Graphics/Cores/Texture/Texture.h"
#include "../Compiler/CompilationCore.h"
#include "../CommonObjects/Empty.h"
#include "../Web/Web.h"
#undef CreateWindow